security:
    encoders:
        App\Entity\User:
            algorithm: auto  # Utilisation de l'algorithme recommandé par Symfony

    # User providers define how users are loaded
    providers:
        # Configure a provider that will load users from your User entity
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username  # Attribut de l'utilisateur utilisé pour l'authentification

    # Firewalls define how users can authenticate
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  # Pas de sécurité pour le mode développeur
        main:
            anonymous: lazy
            provider: app_user_provider  # Fournisseur à utiliser pour ce pare-feu
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: app_logout  # Route à appeler pour se déconnecter

    # Access control rules define which roles have access to different parts of your site
    access_control:
        # Adjust these rules based on your needs
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        encoders:
            # Password hashing settings for the test environment
            App\Entity\User:
                algorithm: auto  # Utilisation de l'algorithme recommandé par Symfony
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
